name: boat_racer_databook
description: "競艇選手データブック"
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  objectbox: ^5.0.2
  objectbox_flutter_libs: ^5.0.2
  path_provider: ^2.1.4
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  objectbox_generator: ^5.0.2
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/members.json
    - assets/icon.png
    - assets/icon_foreground.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon_foreground.png"

dependency_overrides:
  analyzer: 8.3.0
